---
title: "Compressing Non-PTAGIS PIT Tag Data"
author: Kevin See
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Compressing Non-PTAGIS PIT Tag Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = "hide"}
# knitr options
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  comment = "#>"
)

library(knitr)
library(here)
```

```{r load-packages}
library(tidyverse)
# library(PITcleanr)
devtools::load_all()
```

# Introduction

Not all PIT tag data is in PTAGIS. 

**Naming convention for files to determine what type they are**


```{r}
data_path = "O:Documents/Git/Other/PITcleanr_lite/input/"

# what kind of files exist?
file_df <- tibble(file_nm = list.files(data_path)) |> 
  filter(str_detect(file_nm, "\\.")) |> 
  mutate(file_type = if_else(str_detect(file_nm, "BIOLOGIC"),
                             "Biologic_csv",
                             if_else(str_detect(file_nm, "PTAGIS"),
                                     "PTAGIS",
                                     "raw")))

file_df
```


```{r}
# read them all in
all_obs <-
  file_df |> 
  mutate(obs_df = map2(file_nm,
                       file_type,
                       .f = function(x, y) {
                         try(readCTH(paste0(data_path, x), y))
                       })) |> 
  mutate(cls_obs = map_chr(obs_df, .f = function(x) class(x)[1])) |> 
  filter(cls_obs != "try-error") |> 
  select(-cls_obs) |> 
  unnest(obs_df) |> 
  distinct()


# PTAGIS configuration
org_config <- buildConfig()

# Biologic configuration for Henry’s Ranch 
bio_config <- read_csv("O:Documents/Git/Other/PITcleanr_lite/config/site_metadata_revised.csv",
                        show_col_types = F) |> 
  mutate(
    across(
      rkm,
      as.character
    ),
    across(
      antenna_id,
      ~ str_pad(., 
                width = 2,
                side = "left",
                pad = "0")
    )
  ) |> 
  mutate(
    across(
      site_code,
      ~ recode(., 
               "SUB" = "SUB2")
    ),
    node = paste(site_code, antenna_id,
                 sep = "_")
  )

my_config <- org_config |> 
  bind_rows(bio_config)

# compress all detections
test_comp <- compress(all_obs,
                      configuration = my_config)
nrow(all_obs)
nrow(test_comp)
nrow(test_comp) / nrow(all_obs)
```

```{r}
# transform into capture histories of 1's and 0's

# put column names of capture history in correct order
ch_col_nms <- my_config |> 
  select(node, rkm, rkm_total) |> 
  distinct() |> 
  arrange(desc(rkm), desc(rkm_total), node) |> 
  filter(node %in% unique(test_comp$node)) |> 
  # as.data.frame()
  pull(node)

test_comp |> 
  select(tag_code,
         node) |> 
  distinct() |> 
  mutate(seen = 1) |> 
  pivot_wider(names_from = node,
              values_from = seen,
              values_fill = 0) |> 
  select(tag_code,
         any_of(ch_col_nms)) |> 
  # names()
  unite(col = ch,
        -tag_code, 
        sep = "",
        remove = T)
  

```

```{r}
sites_sf <- extractSites(all_obs,
                         as_sf = T,
                         configuration = my_config)

dwn_flw = F
nhd_list = queryFlowlines(sites_sf = sites_sf,
                          root_site_code = "LLR",
                          min_strm_order = 2,
                          dwnstrm_sites = dwn_flw,
                          dwn_min_stream_order_diff = 4)
# compile the upstream and downstream flowlines
flowlines = nhd_list$flowlines
if(dwn_flw) {
  flowlines %<>%
    rbind(nhd_list$dwn_flowlines)
}

ggplot() +
  geom_sf(data = flowlines,
          aes(color = as.factor(StreamOrde),
              size = StreamOrde)) +
  scale_color_viridis_d(direction = -1,
                        option = "D",
                        name = "Stream\nOrder",
                        end = 0.8) +
  scale_size_continuous(range = c(0.2, 1.2),
                        guide = 'none') +
  geom_sf(data = nhd_list$basin,
          fill = NA,
          lwd = 2) +
  geom_sf(data = sites_sf,
          size = 4,
          color = "black") +
  ggrepel::geom_label_repel(
    data = sites_sf,
    aes(label = node_site, 
        geometry = geometry),
    size = 2,
    stat = "sf_coordinates",
    min.segment.length = 0,
    max.overlaps = 50
  ) +
  theme_bw() +
  theme(axis.title = element_blank())

```

