---
output:
  rmarkdown::html_vignette: default
  html_document: default
---

The `queryPtagisMeta()` and `buildConfig()` functions in `PITcleanr` return information from **all** INT and MRR sites in PTAGIS. However, the user may only be interested in those site codes of detections within their complete tag history output downloaded from PTAGIS e.g., your `ptagis_file`. The `extractSites()` function does just that. In addition, the detections can be filtered by a minimum and/or maximum detection date, and the results are returned as either a tibble, or as a simple (spatial) feature `sf` object. Setting the `min_date` argument could be useful if the user is not interested in detections at sites prior to your study period e.g., detections that occur prior to fish arriving at your tagging or release location.

In this example, we create a new object `sites_sf`, return it as an `sf` object `as_sf = T` and only return sites from those detections that occurred after May 1, 2015. We also extract sites only from the Wenatchee subbasin and remove a couple sites that we perhaps don't care about. More information on simple features can be found [here](https://r-spatial.github.io/sf/).

```{r extract-sites}
sites_sf = extractSites(ptagis_file,
                        as_sf = T,
                        min_date = "20150501",
                        configuration = configuration)
# focus on sites within Wenatchee subbasin
sites_sf = sites_sf %>%
  filter(grepl("754.", rkm),
         # remove a few sites we don't care about
         !site_code %in% c("LWE", "ICICLC"))

```
